fix: Formatting error `TypeError: getVisitorKeys is not a function or its return value is not iterable`
Fixed by pinning Prettier to version 3.6.2. Once the underlying issue is resolved, this can be updated to a newer version.

See issue https://github.com/sveltejs/prettier-plugin-svelte/issues/504